# Generated by Django 2.2.2 on 2021-07-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swag_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectortoken',
            name='token',
            field=models.TextField(help_text='"oauth_token" (OAuth1) or access token (OAuth2)', verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='connectortoken',
            name='token_secret',
            field=models.TextField(blank=True, help_text='"oauth_token_secret" (OAuth1) or refresh token (OAuth2)', verbose_name='token secret'),
        ),
    ]
